import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const repoRoot = join(import.meta.dirname, "..", "..");

function serverServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = readFileSync(
    join(repoRoot, "ops", "compose", `docker-compose.${mode}.yml`),
    "utf8",
  );
  const start = text.indexOf("\n  server:");
  expect(start).toBeGreaterThanOrEqual(0);
  const nextService = text.indexOf("\n  sandbox-runner:", start + 1);
  return text.slice(start, nextService === -1 ? undefined : nextService);
}

function frontendServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = composeText(mode);
  const start = text.indexOf("\n  frontend:");
  expect(start).toBeGreaterThanOrEqual(0);
  const nextService = text.indexOf("\n  deployer:", start + 1);
  return text.slice(start, nextService === -1 ? undefined : nextService);
}

function runnerServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = composeText(mode);
  const start = text.indexOf("\n  sandbox-runner:");
  expect(start).toBeGreaterThanOrEqual(0);
  const nextService = text.indexOf("\n  frontend:", start + 1);
  return text.slice(start, nextService === -1 ? undefined : nextService);
}

function composeText(mode: "dev" | "test" | "prod"): string {
  return readFileSync(
    join(repoRoot, "ops", "compose", `docker-compose.${mode}.yml`),
    "utf8",
  );
}

function deployerServiceBlock(mode: "dev" | "test" | "prod"): string {
  const text = composeText(mode);
  const start = text.indexOf("\n  deployer:");
  expect(start).toBeGreaterThanOrEqual(0);
  return text.slice(start);
}

describe("compose server config", () => {
  it("loads server credentials from .server.env and does not publish the API port", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const block = serverServiceBlock(mode);
      // Credentials (OAuth, session, admin) are loaded from .server.env generated by start.sh.
      expect(block).toContain("env_file:");
      expect(block).toContain(".server.env");
      expect(block).toContain("PROVIDER_PROXY_LISTEN_HOST=0.0.0.0");
      // The server API port is never published externally; nginx/frontend is the public face.
      expect(block).not.toContain("8010:8010");
      expect(block).not.toContain("8110:8010");
    }
  });

  it("uses the server compose service as the backend dependency", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const text = composeText(mode);
      expect(text).toContain("\n  server:");
      expect(text).toContain("container_name: rainver-" + mode + "-server");
    }
  });

  it("bind-mounts live server migrations for dev and test one-shot migration runs", () => {
    for (const mode of ["dev", "test"] as const) {
      const block = serverServiceBlock(mode);
      expect(block).toContain(
        "../../server/migrations:/app/server/migrations:ro",
      );
    }
    expect(serverServiceBlock("prod")).not.toContain(
      "../../server/migrations:/app/server/migrations:ro",
    );
    expect(readFileSync(join(repoRoot, "server", "Dockerfile"), "utf8")).toContain(
      "COPY server/migrations ./migrations",
    );
  });

  it("keeps official plugin source out of the production server container", () => {
    for (const mode of ["dev", "test"] as const) {
      expect(serverServiceBlock(mode)).toContain("../../plugins:/app/plugins:ro");
    }
    expect(serverServiceBlock("prod")).not.toContain("../../plugins:");
    expect(readFileSync(join(repoRoot, "server", "Dockerfile"), "utf8")).toContain(
      "COPY plugins /app/plugins",
    );
  });

  it("builds the frontend from the repo root so official plugin pages are included", () => {
    for (const mode of ["dev", "test"] as const) {
      const block = frontendServiceBlock(mode);
      expect(block).toContain("context: ../../");
      expect(block).toContain("dockerfile: apps/web/Dockerfile");
      expect(block).toContain("../../apps/web:/repo/apps/web");
      expect(block).toContain("../../plugins:/repo/plugins:ro");
    }
  });

  it("runs production from the CI-published images and never builds on the host", () => {
    const prod = composeText("prod");
    expect(prod).not.toContain("build:");
    for (const [service, image] of [
      ["server", "rainver-server"],
      ["frontend", "rainver-frontend"],
      ["sandbox-runner", "rainver-sandbox-runner"],
      ["deployer", "rainver-deployer"],
    ] as const) {
      expect(prod).toContain(
        `  ${service}:\n    image: ghcr.io/jyc333/${image}:\${RAINVER_IMAGE_TAG:-stable}`,
      );
    }
    const startScript = readFileSync(join(repoRoot, "ops", "scripts", "start.sh"), "utf8");
    expect(startScript).not.toContain("docker build");
    expect(startScript).toContain('"${COMPOSE[@]}" pull');
    // The prod image carries the publishing commit; a local build leaves it unset.
    const dockerfile = readFileSync(join(repoRoot, "server", "Dockerfile"), "utf8");
    expect(dockerfile).toContain("ENV APP_VERSION=${RAINVER_BUILD_SHA}");
  });

  it("uses distinct loopback-only production host ports by default", () => {
    const prodServer = serverServiceBlock("prod");
    const prodFrontend = frontendServiceBlock("prod");

    expect(prodFrontend).toContain(
      '"${RAINVER_WEB_BIND:-127.0.0.1}:${RAINVER_WEB_PORT:-28400}:80"',
    );
    expect(prodServer).toContain(
      "PROVIDER_PROXY_LISTEN_HOST=0.0.0.0",
    );
    expect(prodServer).toContain(
      "PROVIDER_PROXY_PORT=${PROVIDER_PROXY_PORT:-28421}",
    );
    expect(prodServer).toContain(
      '"${PROVIDER_PROXY_BIND:-127.0.0.1}:${PROVIDER_PROXY_PORT:-28421}:${PROVIDER_PROXY_PORT:-28421}"',
    );
    expect(prodFrontend).not.toContain('"80:80"');
    expect(prodFrontend).not.toContain('"3000:5173"');
    expect(prodServer).not.toContain("PROVIDER_PROXY_PORT=${PROVIDER_PROXY_PORT:-8021}");
  });

  it("keeps runtime product policy and internal defaults out of every env template", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const template = readFileSync(join(repoRoot, "ops", "env", `.env.${mode}.example`), "utf8");
      for (const key of [
        "BACKUP_INTERVAL_HOURS",
        "BACKUP_RETENTION_COUNT",
        "BACKUP_INCLUDE_LOGS",
        "BACKUP_ON_STARTUP",
        "SERVER_DAILY_REPORT_SCHEDULER_ENABLED",
        "SERVER_DAILY_REPORT_SCHEDULER_INTERVAL_SECONDS",
        "SERVER_AUTOMATION_SCHEDULER_ENABLED",
        "SERVER_AUTOMATION_SCHEDULER_INTERVAL_SECONDS",
        "SERVER_MEMORY_ACCESS_LOG_RETENTION_ENABLED",
        "SERVER_MEMORY_ACCESS_LOG_RETENTION_DAYS",
        "SERVER_MEMORY_ACCESS_LOG_PRUNE_INTERVAL_SECONDS",
        "SERVER_INTAKE_EXTRACTION_SCHEDULER_ENABLED",
        "SERVER_INTAKE_EXTRACTION_SCHEDULER_INTERVAL_SECONDS",
        "SERVER_LOG_LEVEL",
        "SERVER_REQUEST_TIMEOUT_MS",
        "RUNTIME_TOOLS_ROOT",
        "DEFAULT_USER_ID",
        "REFLECTOR_MODE",
        "BUILTIN_HOST_MAX_CONCURRENT_RUNS",
        "WORKSPACE_ROOT",
        "SANDBOX_ROOT",
      ]) {
        expect(template, `${mode} template contains ${key}`).not.toContain(key);
      }
    }
    const template = readFileSync(join(repoRoot, "ops", "env", ".env.prod.example"), "utf8");
    expect(template).toContain("BACKUP_ENABLED=true");
    expect(template).toContain("INSTANCE_ADMIN_EMAIL=owner@example.com");
  });

  it("builds the local protocol package before installing frontend dependencies", () => {
    const dockerfile = readFileSync(
      join(repoRoot, "apps", "web", "Dockerfile"),
      "utf8",
    );
    const workspaceInstall = dockerfile.indexOf("RUN pnpm install --frozen-lockfile");
    const protocolBuild = dockerfile.indexOf("WORKDIR /repo/packages/protocol");
    const webInstall = dockerfile.indexOf("WORKDIR /repo/apps/web");

    expect(workspaceInstall).toBeGreaterThanOrEqual(0);
    expect(protocolBuild).toBeGreaterThanOrEqual(0);
    expect(dockerfile.slice(protocolBuild, webInstall)).toContain("RUN pnpm run build");
    expect(webInstall).toBeGreaterThan(protocolBuild);
  });

  it("keeps the privileged deployer socket private to the deployer container", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      expect(deployerServiceBlock(mode)).toContain(
        "DEPLOYER_SOCKET=/tmp/rainver-deployer.sock",
      );
      expect(serverServiceBlock(mode)).not.toContain("deployer.sock");
    }
  });

  it("limits the deployer to a read-only ops mount and the internal-token env", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const block = deployerServiceBlock(mode);
      // B44/ADR 0020 §6: no writable checkout inside the privileged sidecar.
      expect(block).not.toContain("../../:/repo");
      expect(block).toContain("- ../../ops:/repo/ops:ro");
      // The mode root is mounted at its host path so client-side compose reads
      // (env_file) and daemon-side volume sources agree.
      const modeRoot = `\${RAINVER_MODE_ROOT:-$HOME/.rainver-data/${mode}}`;
      expect(block).toContain(`- ${modeRoot}:${modeRoot}`);
      expect(block).toContain(`RAINVER_HOST_MODE_ROOT=${modeRoot}`);
      expect(block).toContain("RAINVER_ENV_FILE_READONLY=1");
      expect(block).toContain(`${modeRoot}/.deployer.env`);
      // The deployer gets the internal token only, never database or session
      // credentials.
      expect(block).not.toContain(".server.env");
      expect(block).not.toContain("POSTGRES_PASSWORD");
    }
  });

  it("hands compose the host mode root and keeps the deployer out of the instance .env", () => {
    const lib = readFileSync(join(repoRoot, "ops", "scripts", "lib", "local-compose.sh"), "utf8");
    expect(lib).toContain('export RAINVER_MODE_ROOT="${RAINVER_HOST_MODE_ROOT:-$MODE_ROOT}"');
    // A container whose two host-path inputs disagree must fail, not read one
    // directory while mounting another.
    expect(lib).toContain('"$RAINVER_HOST_MODE_ROOT" != "$MODE_ROOT"');
    expect(lib).toContain("DEPLOYER_SERVER_URL");
    // B43: creating, editing, or regenerating deployment inputs is refused for a
    // read-only caller — all three write paths, not just one.
    expect(lib.match(/RAINVER_ENV_FILE_READONLY:-0/g)).toHaveLength(3);
    for (const script of ["rebuild.sh", "restart.sh", "health_check.sh"]) {
      const text = readFileSync(join(repoRoot, "deployer", "scripts", script), "utf8");
      expect(text).toContain("HOST_MODE_ROOT=\"${RAINVER_HOST_MODE_ROOT:?");
      expect(text).not.toContain('RAINVER_MODE_ROOT="$INSTANCE_ROOT"');
    }
    // The schema check bind-mounts the checkout; it must refuse rather than let
    // the daemon invent those directories on the host.
    const migrate = readFileSync(join(repoRoot, "ops", "scripts", "db", "migrate.sh"), "utf8");
    expect(migrate).toContain('if [[ ! -d "$REPO_ROOT/server/src" ]]; then');
  });

  it("keeps namespace privileges, and no internal token, on the built-in execution host", () => {
    for (const mode of ["dev", "test", "prod"] as const) {
      const server = serverServiceBlock(mode);
      const runner = runnerServiceBlock(mode);
      expect(server).not.toContain("seccomp=unconfined");
      expect(runner).toContain("seccomp=unconfined");
      expect(runner).toContain("no-new-privileges=true");
      expect(runner).toContain("cap_drop:");
      expect(runner).toContain("read_only: true");
      // No env file at all now. `.runner.env` existed to give the Runner
      // `SANDBOX_RUNNER_TOKEN`, which is the control plane's internal token and
      // unlocks the internal credential and execution routes from the network
      // this container is on. With the Runner gone the token goes with it: the
      // daemon holds a bearer token for its own Host row and nothing else.
      expect(runner).not.toContain(".runner.env");
      expect(runner).not.toContain(".server.env");
      expect(runner).not.toContain("SANDBOX_RUNNER_TOKEN");
      expect(runner).not.toContain(":/rainver");
      expect(runner).not.toContain("docker.sock");
      expect(runner).not.toContain("../../:/repo");
      expect(runner).not.toMatch(/\/cache:\/runner\//);
      // The Runner's six authority roots went with it; what the daemon owns is
      // the instance's workspace root plus its own config directory, and the
      // credential the control plane publishes, which it only reads.
      expect(runner).toContain("workspaces:/runner/workspaces");
      expect(runner).toContain("cache/host-daemon:/runner/host");
      expect(runner).toContain("cache/builtin-host:/runner/builtin-host:ro");
      expect(runner).not.toContain("/runner/run-homes");
      expect(runner).not.toContain("/runner/runtime-tools");
      expect(server).toContain("runner-control");
      expect(runner).toMatch(/networks:\n(?:\s*#.*\n)*\s*- runner-control\n/);
      expect(composeText(mode)).toContain("runner-control:\n    internal: true");
      // The built-in execution host needs outbound Internet of its own — to
      // download a managed copy of a runtime, complete a vendor login, reach a
      // model provider. It gets a bridge nothing else joins, so the container
      // still cannot see the database or a sibling service and nothing can dial
      // in; `runner-control` stays internal beside it.
      expect(runner).toContain("- host-egress");
      expect(composeText(mode)).toContain("  host-egress:");
      // Any service joining it, not just the server: the whole point of the
      // bridge is that the built-in host is alone on it.
      expect(composeText(mode).split("host-egress").length - 1).toBe(2);
    }
    expect(readFileSync(join(repoRoot, "sandbox", "Dockerfile"), "utf8"))
      .toContain("bubblewrap");
    // The Runner is a compose service; start.sh builds no standalone sandbox
    // image and never mounts the sandbox source tree.
    const startScript = readFileSync(join(repoRoot, "ops", "scripts", "start.sh"), "utf8");
    expect(startScript).not.toContain("sandbox/Dockerfile");
    expect(startScript).not.toContain('"$REPO_ROOT/sandbox/"');
    for (const path of ["workspaces", "runtime-tools", "cache/runtime-homes", "cache/conversation-runtime-homes", "cache/login-homes"]) {
      expect(startScript).toContain(`\"$MODE_ROOT/${path}\"`);
    }
  });
});
